"""Generate and patch PyInstaller spec for macOS arm64 builds."""

import pathlib
import subprocess
import sys


def run_command(cmd):
    print(f"$ {' '.join(cmd)}")
    subprocess.check_call(cmd)


def generate_spec():
    """Run PyInstaller to generate an arm64 spec file."""
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        "--name",
        "PhysioClinicAssistant",
        "--windowed",
        "--onedir",
        "--target-arch",
        "arm64",
        "--osx-bundle-identifier",
        "com.physioclinic.assistant",
        "--icon",
        "static/logo.icns",
        "--collect-all",
        "pvrecorder",
        "--collect-all",
        "faster_whisper",
        "--collect-all",
        "llama_cpp",
        "--collect-all",
        "transformers",
        "--hidden-import",
        "tkinter",
        "--hidden-import",
        "tkinter.ttk",
        "--hidden-import",
        "tkinter.messagebox",
        "--hidden-import",
        "tkinter.filedialog",
        "--hidden-import",
        "tkinter.scrolledtext",
        "--hidden-import",
        "_tkinter",
        "--hidden-import",
        "PIL",
        "--hidden-import",
        "PIL._tkinter_finder",
        "--hidden-import",
        "PIL.Image",
        "--hidden-import",
        "PIL.ImageTk",
        "--hidden-import",
        "threading",
        "--hidden-import",
        "multiprocessing",
        "--hidden-import",
        "multiprocessing.pool",
        "--hidden-import",
        "multiprocessing.resource_tracker",
        "--hidden-import",
        "multiprocessing.synchronize",
        "--hidden-import",
        "queue",
        "--hidden-import",
        "plistlib",
        "--hidden-import",
        "pvrecorder",
        "--hidden-import",
        "sounddevice",
        "--hidden-import",
        "faster_whisper",
        "--hidden-import",
        "faster_whisper.transcribe",
        "--hidden-import",
        "faster_whisper.vad",
        "--hidden-import",
        "faster_whisper.audio",
        "--hidden-import",
        "llama_cpp",
        "--hidden-import",
        "llama_cpp_python",
        "--hidden-import",
        "transformers",
        "--hidden-import",
        "transformers.models",
        "--hidden-import",
        "numpy",
        "--hidden-import",
        "numpy.core",
        "--hidden-import",
        "scipy",
        "--hidden-import",
        "scipy.special",
        "--hidden-import",
        "reportlab",
        "--hidden-import",
        "reportlab.pdfgen",
        "--hidden-import",
        "pypdf",
        "--hidden-import",
        "PyPDF2",
        "--hidden-import",
        "sqlite3",
        "--hidden-import",
        "cryptography",
        "--hidden-import",
        "cryptography.fernet",
        "--hidden-import",
        "cryptography.hazmat",
        "--hidden-import",
        "cryptography.hazmat.backends",
        "--hidden-import",
        "cryptography.hazmat.primitives",
        "--hidden-import",
        "supabase",
        "--hidden-import",
        "supabase.client",
        "--hidden-import",
        "supabase.lib",
        "--hidden-import",
        "postgrest",
        "--hidden-import",
        "realtime",
        "--hidden-import",
        "storage3",
        "--hidden-import",
        "httpx",
        "--hidden-import",
        "requests",
        "--hidden-import",
        "certifi",
        "--hidden-import",
        "ssl",
        "--hidden-import",
        "socket",
        "--hidden-import",
        "json",
        "--hidden-import",
        "pkg_resources",
        "--hidden-import",
        "pkg_resources.py2_warn",
        "--hidden-import",
        "packaging",
        "--add-data",
        "config:config",
        "--add-data",
        "forms:forms",
        "--add-data",
        "auth:auth",
        "--add-data",
        "static:static",
        "--add-data",
        "resources:resources",
        "--add-data",
        "app_paths.py:.",
        "--add-data",
        "setup_wizard.py:.",
        "--add-data",
        "system_checker.py:.",
        "--add-data",
        "config_validator.py:.",
        "--add-data",
        "uninstaller.py:.",
        "--add-data",
        "main.py:.",
        "--add-data",
        "VERSION:.",
        "--add-data",
        "README.md:.",
        "--add-data",
        "requirements.txt:.",
        "--clean",
        "--noconfirm",
        "--log-level",
        "WARN",
        "run_app.py",
    ]
    run_command(cmd)


def patch_spec():
    """Ensure target_arch is explicitly set to arm64."""
    spec_path = pathlib.Path("PhysioClinicAssistant.spec")
    text = spec_path.read_text()
    if "target_arch='arm64'" not in text:
        text = text.replace("target_arch=None", "target_arch='arm64'")
        spec_path.write_text(text)
        print("Patched target_arch to arm64 in spec.")
    else:
        print("Spec already targeting arm64.")


def main():
    generate_spec()
    patch_spec()


if __name__ == "__main__":
    main()

